import { copyFile, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface HeadlessCheckResult {
  readonly configPath: string;
  readonly exists: boolean;
  readonly hasPlatforms: boolean;
  readonly projectCount: number;
  readonly issues: ReadonlyArray<string>;
  readonly ok: boolean;
}

export interface HeadlessMigrateResult {
  readonly outputPath: string;
  readonly written: boolean;
  readonly message: string;
}

const PLATFORM_MARKERS = [
  /\[projects\.platforms\]/,
  /\[projects\.platforms\./,
  /^\s*type\s*=\s*["']?feishu["']?/m,
];

function countProjects(content: string): number {
  return (content.match(/\[\[projects\]\]/g) ?? []).length;
}

function hasPlatformSections(content: string): boolean {
  return PLATFORM_MARKERS.some((re) => re.test(content));
}

export function stripPlatformBlocks(content: string): string {
  const lines = content.split("\n");
  const out: string[] = [];
  let skip = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (/^\[projects\.platforms/.test(trimmed)) {
      skip = true;
      continue;
    }
    if (skip) {
      if (/^\[/.test(trimmed) && !/^\[projects\.platforms/.test(trimmed)) {
        skip = false;
      } else {
        continue;
      }
    }
    out.push(line);
  }

  return `${out.join("\n").trim()}\n`;
}

export async function checkHeadlessConfig(
  configPath: string,
): Promise<HeadlessCheckResult> {
  const issues: string[] = [];
  let content = "";
  let exists = false;

  try {
    content = await readFile(configPath, "utf8");
    exists = true;
  } catch {
    issues.push(`配置文件不存在: ${configPath}`);
    return {
      configPath,
      exists: false,
      hasPlatforms: false,
      projectCount: 0,
      issues,
      ok: false,
    };
  }

  const hasPlatforms = hasPlatformSections(content);
  const projectCount = countProjects(content);

  if (hasPlatforms) {
    issues.push(
      "检测到 [projects.platforms] — cc-connect 三 Bot 应迁移为 headless（仅 agent + api.sock）",
    );
  }
  if (projectCount === 0) {
    issues.push("未找到 [[projects]] 定义");
  }
  if (projectCount > 0 && projectCount < 3) {
    issues.push(
      `仅 ${projectCount} 个 project，建议配置 workspace-claude/codex/cursor`,
    );
  }

  return {
    configPath,
    exists: true,
    hasPlatforms,
    projectCount,
    issues,
    ok: exists && !hasPlatforms && projectCount >= 1,
  };
}

function escapeTomlString(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}

/** @internal 测试导出 */
export const escapeTomlStringForTest = escapeTomlString;

export async function loadHeadlessTemplate(workDir: string): Promise<string> {
  const here = dirname(fileURLToPath(import.meta.url));
  const templatePath = join(
    here,
    "../../config/cc-connect.headless.example.toml",
  );
  const raw = await readFile(templatePath, "utf8");
  return raw.replace(
    /work_dir = ".*"/g,
    `work_dir = "${escapeTomlString(workDir)}"`,
  );
}

export async function buildHeadlessContent(
  sourcePath: string,
  workDir: string,
  headerLines: ReadonlyArray<string> = [
    "# Generated by dev-brain migrate-headless",
    `# Source: ${sourcePath}`,
    "",
  ],
): Promise<string> {
  const check = await checkHeadlessConfig(sourcePath);
  let body: string;

  if (check.exists) {
    const source = await readFile(sourcePath, "utf8");
    body = check.hasPlatforms ? stripPlatformBlocks(source) : source;
  } else {
    body = await loadHeadlessTemplate(workDir);
  }

  if (!body.includes("[[projects]]")) {
    body = await loadHeadlessTemplate(workDir);
  }

  return `${headerLines.join("\n")}${body}`;
}

export async function migrateToHeadless(options: {
  readonly sourcePath: string;
  readonly outputPath: string;
  readonly workDir: string;
  readonly dryRun?: boolean;
}): Promise<HeadlessMigrateResult> {
  const output = await buildHeadlessContent(
    options.sourcePath,
    options.workDir,
  );

  if (options.dryRun) {
    return {
      outputPath: options.outputPath,
      written: false,
      message: `dry-run: would write ${options.outputPath} (${output.length} bytes)`,
    };
  }

  await writeFile(options.outputPath, output, "utf8");
  return {
    outputPath: options.outputPath,
    written: true,
    message: `已写入 headless 配置: ${options.outputPath}`,
  };
}

export interface HeadlessApplyResult {
  readonly configPath: string;
  readonly backupPath: string;
  readonly applied: boolean;
  readonly message: string;
}

export async function applyHeadlessConfig(options: {
  readonly sourcePath: string;
  readonly workDir: string;
  readonly dryRun?: boolean;
}): Promise<HeadlessApplyResult> {
  const check = await checkHeadlessConfig(options.sourcePath);
  if (check.ok) {
    return {
      configPath: options.sourcePath,
      backupPath: "",
      applied: false,
      message: "配置已是 headless，无需切换。",
    };
  }

  const backupPath = `${options.sourcePath}.bak.${Date.now()}`;
  if (options.dryRun) {
    return {
      configPath: options.sourcePath,
      backupPath,
      applied: false,
      message: `dry-run: would backup to ${backupPath} and apply headless`,
    };
  }

  const content = await buildHeadlessContent(
    options.sourcePath,
    options.workDir,
    [
      "# Applied by dev-brain migrate-headless --apply",
      `# Backup: ${backupPath}`,
      "",
    ],
  );

  await copyFile(options.sourcePath, backupPath);
  await writeFile(options.sourcePath, content, "utf8");

  return {
    configPath: options.sourcePath,
    backupPath,
    applied: true,
    message: `已应用 headless 配置。备份：${backupPath}。请重启 cc-connect daemon。`,
  };
}

export function formatHeadlessCheckReport(check: HeadlessCheckResult): string {
  const lines = [
    "🔧 cc-connect Headless 检查",
    `- 路径: ${check.configPath}`,
    `- 存在: ${check.exists ? "yes" : "no"}`,
    `- projects: ${check.projectCount}`,
    `- platforms: ${check.hasPlatforms ? "yes (需迁移)" : "no"}`,
    `- 结论: ${check.ok ? "✅ headless 就绪" : "⚠️ 需迁移"}`,
  ];
  if (check.issues.length) {
    lines.push("", "问题:", ...check.issues.map((i) => `- ${i}`));
  }
  return lines.join("\n");
}
